### ISSUE TITLE
Short notation for entry_schema and key_schema

### ISSUE THREAD

**Issue by philippemerle** [oasis-open/tosca-community-contributions#102]
**Issue Description**

Following illustrates the short notation for entry_schema and key_schema
```yaml
tosca_definitions_version: tosca_simple_yaml_1_3
data_types:
  DT:
    properties:
      p-list:
        type: list
        entry_schema: integer
      p-map:
        type: map
        key_schema: integer
        entry_schema: integer
```
This template is valid with Ubicity Validator, Puccini, and Cloudnet TOSCA toolbox at least.

However, this short notation is not *explicitly* specified into Section 3.6.9 Schema Definition of TOSCA 1.3 and Section 4.4.5 Schema definition of TOSCA 2.0 csd03.

**Proposed Resolution**

Add the following at the beginning of Section 4.4.5.2 of TOSCA 2.0.

```
4.4.5.2.1 Short notation

The following single-line grammar may be used when only the schema type needs to be declared:

<schema_definition>: <schema_type>

4.4.5.2.2 Extended notation
```

Replace
```
Schema definitions have the following grammar:
```
by
```
The following multi-line grammar may be used when additional information on the schema definition is needed:
```
