### ISSUE TITLE
Add support for capability filters in requirement definitions (and requirement assignments)

### ISSUE THREAD

**Issue by lauwers** [oasis-open/tosca-community-contributions#118]
Requirement definitions and assignments support a node_filter keyword to narrow down the set of target nodes that can be used to fulfill a requirement. This keyword presumes that the node type of the target node is provided (using the node keyword in the requirement definition or requirement assignment). When the node type is not specified, target filters can not be applied. To remedy this situation, we should add support for capability filters that narrow down the set of possible targets based on constraints on the values of the properties of the target capability.
To harmonize support for node filters and capability filters, I propose that we introduce an extended notation for defining target capability type and target node types in requirement definitions as in the following example:
```
requirements:
  - provider:
      capability:
        type: ProviderCapability
        filter: 
          properties:
            performance: { equal: "high" }
      node:
        type: ServiceProvider
        filter:
          properties:
            vendor: { equal: "ACME" "
```
 Similar syntax would be used inside the requirement assignment. Of course, if no filters are provided, the old single-line syntax should still work.
