### ISSUE TITLE
Clarification on usage of TOSCA grammar to define objects in Metadata 

### ISSUE THREAD

**Issue by abhishek-kumar0409** [oasis-open/tosca-community-contributions#126]
As it is evident from the standards, the data type of the metadata is a map of strings. I've come across some VNF Descriptors that use map of strings along with expressions as shown in the below example.

e.g.
```
input:
    security_group_0: "default"
    security_group_1: "custom"
node_template:
    vdu_a
        type: tosca.nodes.x.y.z.
        properties:
             k1: v1
        metadata:
            security_groups: { get_input: security_group_0}
```

In this example, the assumption is made that the security group is pre-created by the cloud administrators. And, the VNF-D designer has to simply reference the name of the security group name in the VNF-D, without creating the security groups in the Openstack. Some designers may use inputs section to define the value of the security group or any other k-V parameters and use get_input property to . 

Perhaps it is not evident for the TOSCA grammar whether the objects defined in the metadata section is map of strings or map of strings with expression.

`Question - Is it allowed to define values as map of string with expressions in the metadata ?`
