### ISSUE TITLE
Are functions allowed in constraint clauses

### ISSUE THREAD

**Issue by lauwers** [oasis-open/tosca-community-contributions#129]
I believe we all agree that functions are allowed in filter definitions (which in v1.3 were defined using constraint clauses). But what about regular constraint clauses in property definitions? Are functions allowed in those definitions? For example, is the following valid?
```
tosca_definitions_version: tosca_simple_yaml_1_3

node_types:

  NodeType:
    properties:
      minimum_instances:
        type: integer
        constraints:
          - greater_or_equal: 0 # positive integer
      maximum_instances:
        type: integer
        constraints:
          - greater_or_equal: { get_property: [SELF, minimum_instances]}
      default_instances:
        type: integer
        constraints:
          - greater_or_equal: { get_property: [SELF, minimum_instances]}
          - less_or_equal: { get_property: [SELF, maximum_instances]}
        required: false
```
