### ISSUE TITLE
Use functions for constraints in order to unify expression language

### ISSUE THREAD

**Issue by tliron** [oasis-open/tosca-community-contributions#132]
As discussed last week, here is a proposal for how it could look.

Three concepts are introduced:

1) `validation` keyname (instead of `constraints`) that is simply a boolean expression. It must evaluate to true for the value to be valid. Any expression can be used with any function with any degree of nesting.
2) A new `VAL` special name that refers to the current value, which can be used as the first argument in `$get_property` like `SELF`, `TARGET`, etc.
3) And `$VAL` as a shortcut for `{ $get_property: [ VAL ] }`

Examples:

```yaml
data_types:

  # "validation" is a boolean expression that must evaluate to true for the value to be valid
  # If not specified, it's as if it was "validation: true"
  # The special name "VAL" can be used with "$get_property" to refer to the value
  Count1:
    derived_from: integer
    validation: { $greater_or_equal: [ { $get_property: [ VAL ] }, 0 ] }

  # Because the above is cumbersome, let's introduce "$VAL" (escapable) as a shortcut
  Count2:
    derived_from: integer
    validation: { $greater_or_equal: [ $VAL, 0 ] }

  # Function calls can be nested with boolean logic functions, such as "$or" and "$and"
  # and really any function can be called
  Host:
    derived_from: string
    validation:
      $or:
      - { $pattern: [ $VAL, ^((25[0-5]|(2[0-4]|1\d|[1-9]|)\d)(\.(?!$)|$)){4}$ ] } # IPv4
      - $and:
        - { $equals: [ $VAL, localhost ] }
        - { $get_input: [ allow-names ] } # boolean input type

  # Powerful validations are possible across properties in a complex type
  # (impossible with the existing constraint system)
  FrequencyRange:
    properties:
      low:
        type: scalar-unit.frequency
      high:
        type: scalar-unit.frequency
    validation:
      $greater_or_equal: [ { $get_property: [ VAL, high ] }, { $get_property: [ VAL, low ] } ]

  # The following type refers to SELF, which means it can only be used in contexts in which SELF
  # exists and has the right property (see "Compute" node type below)
  MaxRAM:
    derived_from: scalar-unit.size
    validation:
      $greater_or_equal: [ $VAL, { $get_property: [ SELF, min-ram ] } ]

node_types:

  Compute:
    properties:
      min-ram:
        type: scalar-unit.size
      max-ram:
        type: MaxRAM # this will work because we have "SELF.min-ram"
```

**Comment by tliron** [comment]
Feedback:

1) "VAL" is confusing, sounds like "validation". Perhaps it should be "VALUE"?
2) The call site within data types does not include SELF or an ability to call get_input. A call site with those would be assigned only when used in a node or relationship context. TOSCA processors may not all be happy with referring to SELF in data types.

**Comment by tliron** [comment]
Instead of reusing $get_property, we can introduce a new TOSCA-path-aware function, $get_value (and then we don't need the special name "VAL"):

```yaml
  Count1:
    derived_from: integer
    validation: { $greater_or_equal: [ { $get_value: [] }, 0 ] }

  Count2:
    derived_from: integer
    validation: { $greater_or_equal: [ $VALUE, 0 ] }

  FrequencyRange:
    properties:
      low:
        type: scalar-unit.frequency
      high:
        type: scalar-unit.frequency
    validation:
      $greater_or_equal: [ { $get_value: [ high ] }, { $get_value: [ low ] } ]
```

**Comment by pmjordan** [comment]
If we do decide that the shortcut is desireable then rather that it being '$VALUE' we should consider
using '$THIS_VALUE'. Although this is more verbose it makes it clearer that it means get_value with an empty set, i.e. without any path. 
If you want it to be really short AND discourage further syntax extensions of this kind then it could be '$_' although I don't like that much.

I'm not totally convinced the short cut is worth it. Would the following be valid and equivalent to the first example ? 



    Count1:
    derived_from: integer
    validation: { $greater_or_equal: [ { $get_value: [Count1] }, 0 ] }

**Comment by lauwers** [comment]
We should consider making our function syntax more flexible, and adopt the following:

- Any string that starts with a `$` is interpreted to be a function name. This makes `$` a reserved character in TOSCA. String names that start with `$` and that are not functions must be escaped.
- Functions that don't take any arguments don't need to use `map` syntax. For example 

```
Count:
    derived_from: integer
    validation: { $greater_or_equal: [ $get_value, 0] }
```
 is the same as 
```
Count:
    derived_from: integer
    validation: { $greater_or_equal: [ { $get_value: [] }, 0] }
```
- Functions that take only one argument don't need to use the 'list' syntax for arguments. For example
```
NonZero:
    derived_from: integer
    validation: { $not: { $equal: [ {$get_value: [] }, 0 ] }
```
 is the same as
```
NonZero:
    derived_from: integer
    validation: { $not: [ { $equal: [ {$get_value: [] }, 0 ] ] }
```
I think this would simplify function syntax without introducing additional parsing challenges.

**Comment by pmjordan** [comment]
The propsal from @lauwers looks good but I have one question: If I were writing a custom function which took only one argument would I have to write it so that had the capability to accept
a) the argument 
and also as an alternative
b) a list with one entry which contained the argument?
if so then not so great, it would better if the TOSCA parser did that for me and passed only one of those possibilities, in which case we would have to specifiy which one.

**Comment by calincurescu** [comment]
Some input regarding what functions would be useful for both conditions and constraints and have them as supported by default (all of them boolean):
1. Functions that could work for both lists (seq) and strings:
is_suffix (string - string, value/list - list)
is_prefix (string - string, value/list - list)
is_contained (string - string, value/list - list)

2. Functions to check if is a value or key in a list/map
values_of (value/list - list, value/list - map)
keys_of (value/list - map)

3. Boolean logic functions:
and, or, not, xor, eq, imp

4. forall and exists:
Functions that apply another function (given as the 1st argument) to each of the elements of the list (2nd argument) and a value (3rd argument).
e.g.: 
$forall: [equal, [el1, el2, ... eln], value]]
$exists: [equal, [el1, el2, ... eln], value]]
Note1: we do not write equal with $ since we do not want to evaluate equal before evaluating forall
Note2: arg1 must be a string that resolves to a boolean function name, arg2 must be a list.

**Comment by tliron** [comment]
In today's ad hoc with proposed a general syntax for magic words in TOSCA, see issue #133.

With that in mind we proposed that the function to use to retrieve the current value in constraint contexts be `$value`. Examples based on the original post above:

```yaml
data_types:

  # Full syntax with no arguments
  Count1:
    derived_from: integer
    validation: { $greater_or_equal: [ { $value: [] }, 0 ] }

  # Magic word
  Count2:
    derived_from: integer
    validation: { $greater_or_equal: [ $value, 0 ] }

  # Full syntax with arguments
  FrequencyRange:
    properties:
      low:
        type: scalar-unit.frequency
      high:
        type: scalar-unit.frequency
    validation:
      $greater_or_equal: [ { $value: [ high ] }, { $value: [ low ] } ]
```
