### ISSUE TITLE
Is the node field optional or mandatory in a requirement assignment?

### ISSUE THREAD

**Issue by philippemerle** [oasis-open/tosca-community-contributions#151]
The following topology template:
```yaml
tosca_definitions_version: tosca_simple_yaml_1_3
topology_template:
  node_templates:
    my_node:
      type: tosca.nodes.Root
      requirements:
        - dependency:
            capability: feature
```
seems to be correct according to the first table in section 3.8.2.1 of TOSCA 1.3 where the `node` field is optional (`no` in Required colunm). But the specification seems to not define the semantics of a requirement assignment with no `node`.

Proposition:
1. Define the semantics of a requirement assignment with no `node` or
2. Make `node` required in  the first table in section 3.8.2.1 of TOSCA 1.3.

Perhaps this should be also applied to TOSCA 2.0 https://docs.oasis-open.org/tosca/TOSCA/v2.0/csd05/TOSCA-v2.0-csd05.html#_Toc125468590.
