### ISSUE TITLE
Consider the restriction that relationships may only be between leaf nodes

### ISSUE THREAD

**Issue by pmjordan** [oasis-open/tosca-community-contributions#94]
There seems to be an implict restriction that relationships may only exist between leaf nodes types.

Consider:
        Node type A has a child node type A'
        Node type B has a child node type B'
        Relationship X has a child relationship type X'
        Node Type A is related via X to Node Type B

The topology comprises Node instances of Type A' and Type B'
I would expect node instance A' to be related to instance B' via relation instance of type X via inheritance but implementations I have experienced would not look for any relationships between A' and B' unless they are explictly defined in A' and/or B'

**Comment by philippemerle** [comment]
@pmjordan: Is the following template illustrated your issue?

```yaml
tosca_definitions_version: tosca_simple_yaml_1_3
capability_types:
  C: {}
relationship_types:
  X:
    valid_target_types: [C]
  Xx:
    derived_from: X
node_types:
  A:
    requirements:
      - x:
          capability: C
  A':
    derived_from: A
  B:
    capabilities:
      c:
        type: C
  B':
    derived_from: B
topology_template:
  node_templates:
    n1:
      type: A'
    n2:
      type: B'
```

Parsing this file with Cloudnet TOSCA toolbox produces the following trace:
```sh
$ translate issue_94.yaml 
Translate issue_94.yaml...
[Info] issue_94.yaml: TOSCA syntax checking
[Info] issue_94.yaml: No service template catalog to load.
[Info] issue_94.yaml: TOSCA type checking...
[Warning] issue_94.yaml@14,23:node_types:A:requirements:x:relationship: undefined but X or Xx are compatible with C!
[Info] issue_94.yaml: topology_template:node_templates:n1:requirements:x - n2 node template found
[Info] issue_94.yaml: TOSCA type checking done.
....
```

So the requirement `x` of `n1` is fulfilled by `n2` as shown in the following generated diagram:
![issue_94-uml2-component-diagram2](https://user-images.githubusercontent.com/770247/158260898-016ce7b5-1354-4f7c-9d82-4f0f4c34190e.png)

So what is the issue?
