### ISSUE TITLE
capability definition properties refinement

### ISSUE THREAD

**Issue by philippemerle** [oasis-open/tosca-community-contributions#98]
Do you consider that the following template is TOSCA-compliant?

```yaml
tosca_definitions_version: tosca_simple_yaml_1_3
node_types:
  MicroService:
    derived_from: tosca.nodes.Root
    capabilities:
      ms_endpoint:
        type: tosca.capabilities.Endpoint
  MS1:
    derived_from: MicroService
    capabilities:
      ms_endpoint: # capability refinement
        properties:
          protocol: http # shortcut equivalent to { value: http }
          port: 3000
          url_path: api/v1/ms1
  MS2:
    derived_from: MicroService
    capabilities:
      ms_endpoint: # capability refinement
        properties:
          protocol: http
          port: 3000
          url_path: api/v1/ms2
```

TOSCA 1.3 seems to say nothing about capability definition properties refinement.

@lauwers : this template is validated by both Ubicity Validator and my own parser.

TOSCA 2.0 is more precise about capability definition properties refinement in a node type, see sentence `properties: not applicable to the definitions in the parent node type but to the definitions in the capability type referred by the type keyname (see grammar above for the rules)` in Section 4.3.5.2.3. If I understand well this constraint then my previous template is TOSCA 2.0 compliant.

Any opinions?
