### ISSUE TITLE
concat function

### ISSUE THREAD

**Issue by philippemerle** [oasis-open/tosca-community-contributions#99]
The TOSCA specification says that `The concat function is used to concatenate two or more string values within a TOSCA service template.`

For the following service template

```yaml
tosca_definitions_version: tosca_simple_yaml_1_3
node_types:
  MySoftware:
    derived_from: tosca.nodes.SoftwareComponent
    capabilities:
      endpoint:
        type: tosca.capabilities.Endpoint
topology_template:
  node_templates:
    compute:
      type: tosca.nodes.Compute
      attributes:
        public_address: my.compute.com
    software:
      type: MySoftware
      capabilities:
        endpoint:
          properties:
            protocol: http
            port: 3000
            url_path: api/v1/software
      requirements:
        - host: compute
  outputs:
    my_software_endpoint_url:
      type: string
      value:
        concat:
          - get_property: [software, endpoint, protocol]
          - "://"
          - get_attribute: [compute, public_address]
          - ":"
          - get_property: [software, endpoint, port]
          - "/"
          - get_property: [software, endpoint, url_path]
```

one could expect that the value of the `my_software_endpoint_url` output will be `http://my.compute.com:3000/api/v1/software`.

But here, the 5th parameter of the `concat` function is not a string but a PortDef integer.

Processing this service template with different TOSCA parsers produces different behaviors:
* No error with Puccini
* No error with Ubicity Validator after removing the line `type: string` else one parsing error
* No error with xOpera parser but one runtime exception when trying to get the outputs after deploying the template
* One typing error (i.e. the 5th parameter is not a string) with Cloudnet TOSCA toolbox

So the given service template is not portable to various TOSCA implementations.

Then the specification of the TOSCA `concat` function should be improved to clearly define that:
* each parameter SHALL BE of type string XOR each parameter SHALL BE convertible to a string, e.g. a PortDef integer could be stringified
* if convertible, which types can be convertible to a string? Is a complex data type convertible?
* what happens if a parameter refers to an unset attribute/property? Is it a parsing error? is it a runtime error? Does the parameter set to an empty string? other behavior?

Any opinions?
